### ISSUE TITLE
Table creation with sqlite?

### ISSUE THREAD

**Issue by pwFoo** [Level-2/Maphper#65]
Hi,
is table creation with sqlite supported at the moment?
```
Fatal error: Uncaught Exception: Invalid query in /srv/maphper/Maphper/DataSource/SqliteAdapter.php:27 Stack trace: #0 /srv/maphper/Maphper/DataSource/DatabaseCrud.php(98): Maphper\DataSource\SqliteAdapter->query(Object(Maphper\Lib\Query)) #1 /srv/maphper/Maphper/DataSource/DatabaseCrud.php(91): Maphper\DataSource\DatabaseCrud->tryUpdate('blog', Array, Object(stdClass)) #2 /srv/maphper/Maphper/DataSource/DatabaseCrud.php(53): Maphper\DataSource\DatabaseCrud->insert('blog', Array, Object(stdClass)) #3 /srv/maphper/Maphper/DataSource/DatabaseCrud.php(62): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), false) #4 /srv/maphper/Maphper/DataSource/Database.php(56): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), true) #5 /srv/maphper/Maphper/Maphper.php(97): Maphper\DataSource\Database->save(Object(stdClass)) #6 /srv/maphper/index.php(27): Maphper\Maphper->offsetSet(NULL, Object(stdClass)) #7 {main} thrown in /srv/maphper/Maphper/DataSource/SqliteAdapter.php on line 27
```

**Comment by pwFoo** [comment]
Create referenced tables isn't supported (like "$blog->author->name").  My demo code works fine with mysql and without the referenced object.
```
error_reporting(E_ALL);
ini_set('display_errors', 1);

spl_autoload_register(function ($class_name) {

    include_once (__dir__ . '/' . str_replace('\\', '/', $class_name) . '.php');
});

$pdo = new PDO('mysql:dbname=maphper;host=mysql', 'maphper', 'maphper');
$blogSource = new \Maphper\DataSource\Database($pdo, 'blog', 'id', array('editmode' => true));
$blogs = new \Maphper\Maphper($blogSource);

$authorSource = new \Maphper\DataSource\Database($pdo, 'author', 'id');
$authors = new \Maphper\Maphper($authorSource);

$relation = new \Maphper\Relation\One($authors, 'authorId', 'id');
$blogs->addRelation('author', $relation);

$blog = new StdClass();
$blog->title = "First article";
$blog->content = "My first article!";
//$blog->author = new StdClass();
//$blog->author->name = 'Andre';

$blogs[] = $blog;
```

Same code changed to sqlite database fails with error message above:
```
$pdo = new PDO('sqlite:database.sqlite3');
```
Database file is created before with sqlite3 console.

**Comment by pwFoo** [comment]
Referenced tables creation works with mysql! editmode was missing with second source!

But will support added for sqlite?

**Comment by pwFoo** [comment]
I don't know how to create PR with git(hub) and don't have found the source code position to fix it, but it looks like the wrong quoting marks used for sqlite (would the same for pgsql I think)?

GeneralEditDatabase.php
```
    public function quote($str) {
		return '`' . str_replace('.', '`.`', trim($str, '`')) . '`';
	}
```

MySQL uses backtick, but pgsql and sqlite use `"`!

I found a pdo wrapper should work for mysql, sqlite and postgesql and there are TWO special cases.
Here is my fork with the important lines.

https://github.com/pwFoo/DByte/blob/master/DByte/DB.php#L12
```
        switch ($pdo->getAttribute(\PDO::ATTR_DRIVER_NAME)) {
            case "mysql": 
                $this->marks = '`';
                $this->pgsql = false;
                break;
            case "sqlite":
                $this->marks = '"';
                $this->pgsql = false;
                break;
            case "pgsql":
                $this->marks = '"';
                $this->pgsql = true;
                break;
        }
```

Used in insert / update method "here":https://github.com/pwFoo/DByte/blob/master/DByte/DB.php#L115:
```
	public function insert($table, array $data)
	{
               // SEE $THIS->MARKS !!! 
		$query = "INSERT INTO {$this->marks}$table{$this->marks} ({$this->marks}" . implode("{$this->marks}, {$this->marks}", array_keys($data))
			. "{$this->marks}) VALUES (" . rtrim(str_repeat('?, ', count($data = array_values($data))), ', ') . ')';
		return $this->pgsql  // IF PGSQL !!!
			? DB::column($query . " RETURNING {$this->marks}id{$this->marks}", $data)
			: (DB::query($query, $data) ? static::$c->lastInsertId() : NULL);
	}
```

I think you need to set different quoting marks for 
1. mysql
2. sqlite / postgres

And pgsql return value for insert is built different.

Database Adapter quoting mark should be a variable with different values for different pdo backends.

Orignal class is static and works with a quoting mark replace in string (don't know if it's better for performance than quoting marks as class property? I changed it for readability and to understand why...)):
https://github.com/Xeoncross/DByte/blob/master/DByte/DB.php#L93

**Comment by pwFoo** [comment]
```
INSERT INTO `author` (name, id) VALUES ( :name, :id )
UPDATE `author` SET `name` = :name, `id` = :id WHERE `id` = :id
INSERT INTO `author` (name, id) VALUES ( :name, :id )
UPDATE `author` SET `name` = :name, `id` = :id WHERE `id` = :id

Fatal error: Uncaught Exception: Invalid query in /srv/v2/core/Maphper/DataSource/SqliteAdapter.php:28 Stack trace: #0 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(98): Maphper\DataSource\SqliteAdapter->query(Object(Maphper\Lib\Query)) #1 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(91): Maphper\DataSource\DatabaseCrud->tryUpdate('author', Array, Object(stdClass)) #2 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(53): Maphper\DataSource\DatabaseCrud->insert('author', Array, Object(stdClass)) #3 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(62): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), false) #4 /srv/v2/core/Maphper/DataSource/Database.php(56): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), true) #5 /srv/v2/core/Maphper/Maphper.php(97): Maphper\DataSource\Database->save(Object(stdClass)) #6 /srv/v2/core/Maphper/Relation/One.php(87): Maphper\Maphper->offsetSet(NULL, Object(stdClass)) #7 /srv/v2/core/Maphper/Lib/Entity.php(31): Maphper\Relation\One->overwrite(Object(stdClass), Object(stdC in /srv/v2/core/Maphper/DataSource/SqliteAdapter.php on line 28
```

**Comment by garrettw** [comment]
It looks like double quotes `"` can be used even in MySQL if you do:
```
SET SQL_MODE=ANSI_QUOTES;
```

**Comment by pwFoo** [comment]
The database / sql parts are confusing... Many small files with different parts. I have problems to follow the involved files...

Changed CrudBuilder.php and tested again, but the same error message.

```
INSERT INTO "author" (name, id) VALUES ( :name, :id )
UPDATE "author" SET "name" = :name, "id" = :id WHERE "id" = :id
INSERT INTO "author" (name, id) VALUES ( :name, :id )
UPDATE "author" SET "name" = :name, "id" = :id WHERE "id" = :id

Fatal error: Uncaught Exception: Invalid query in /srv/v2/core/Maphper/DataSource/SqliteAdapter.php:28 Stack trace: #0 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(98): Maphper\DataSource\SqliteAdapter->query(Object(Maphper\Lib\Query)) #1 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(91): Maphper\DataSource\DatabaseCrud->tryUpdate('author', Array, Object(stdClass)) #2 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(53): Maphper\DataSource\DatabaseCrud->insert('author', Array, Object(stdClass)) #3 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(62): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), false) #4 /srv/v2/core/Maphper/DataSource/Database.php(56): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), true) #5 /srv/v2/core/Maphper/Maphper.php(97): Maphper\DataSource\Database->save(Object(stdClass)) #6 /srv/v2/core/Maphper/Relation/One.php(87): Maphper\Maphper->offsetSet(NULL, Object(stdClass)) #7 /srv/v2/core/Maphper/Lib/Entity.php(31): Maphper\Relation\One->overwrite(Object(stdClass), Object(stdC in /srv/v2/core/Maphper/DataSource/SqliteAdapter.php on line 28
```

**Comment by TRPB** [comment]
This shouldn't be necessary. All the SQLite tests pass and work as intended. What version of PHP are you using?

**Comment by TRPB** [comment]
```
phpunit --filter SqliteDatabaseTest::testCreateTable
PHPUnit 7.4.4 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 420 ms, Memory: 8.00MB

OK (1 test, 2 assertions)
```

Which does the following:

```

	public function testCreateTable() {

		if ($this->tableExists('foo')) {
			$this->dropTable('foo');
		}

		$this->assertFalse($this->tableExists('foo'));

		$mapper = new \Maphper\Maphper($this->getDataSource('foo', 'id', ['editmode' => true]));
		$blog = new stdclass;
		$blog->title = 'Foo';
		$mapper[] = $blog;
		$this->assertTrue($this->tableExists('foo'));
	}
```

It creates the table and works fine. All the tests pass here so no changes to the code to change backticks should be required.

**Comment by pwFoo** [comment]
PHP 7.3.
Code checked and reduced to the needed lines:
```
$pdo = new PDO('sqlite:database.sqlite3');

$blogSource = new \Maphper\DataSource\Database($pdo, 'blog', 'id', array('editmode' => true));
$blogs = new \Maphper\Maphper($blogSource);

$blog = new StdClass();
$blog->title = "First article";
$blog->content = "My first article!";

$blogs[] = $blog;
```

Still same error
```
Fatal error: Uncaught Exception: Invalid query in /srv/v2/core/Maphper/DataSource/SqliteAdapter.php:27 Stack trace: #0 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(98): Maphper\DataSource\SqliteAdapter->query(Object(Maphper\Lib\Query)) #1 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(91): Maphper\DataSource\DatabaseCrud->tryUpdate('blog', Array, Object(stdClass)) #2 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(53): Maphper\DataSource\DatabaseCrud->insert('blog', Array, Object(stdClass)) #3 /srv/v2/core/Maphper/DataSource/DatabaseCrud.php(62): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), false) #4 /srv/v2/core/Maphper/DataSource/Database.php(56): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), true) #5 /srv/v2/core/Maphper/Maphper.php(97): Maphper\DataSource\Database->save(Object(stdClass)) #6 /srv/v2/index.php(33): Maphper\Maphper->offsetSet(NULL, Object(stdClass)) #7 {main} thrown in /srv/v2/core/Maphper/DataSource/SqliteAdapter.php on line 27
```

**Comment by pwFoo** [comment]
Seems empty `$stmt` is the problem?
```
	public function query(\Maphper\Lib\Query $query) {
        $stmt = $this->stmtCache->getCachedStmt($query->getSql());
		$args = $query->getArgs();
     
        //Handle SQLite when PDO_ERRMODE is set to SILENT
        if ($stmt === false) throw new \Exception('Invalid query');
```
https://github.com/Level-2/Maphper/blob/master/Maphper/DataSource/SqliteAdapter.php#L23

**Comment by pwFoo** [comment]
Hi @TRPB 
I tested it again with a clean new setup. 

I found two problems
1. If the table not exists I still get the same error
```
Fatal error: Uncaught Exception: Invalid query in /srv/Maphper/DataSource/SqliteAdapter.php:27 Stack trace: #0 /srv/Maphper/DataSource/DatabaseCrud.php(98): Maphper\DataSource\SqliteAdapter->query(Object(Maphper\Lib\Query)) #1 /srv/Maphper/DataSource/DatabaseCrud.php(91): Maphper\DataSource\DatabaseCrud->tryUpdate('blog', Array, Object(stdClass)) #2 /srv/Maphper/DataSource/DatabaseCrud.php(53): Maphper\DataSource\DatabaseCrud->insert('blog', Array, Object(stdClass)) #3 /srv/Maphper/DataSource/DatabaseCrud.php(62): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), false) #4 /srv/Maphper/DataSource/Database.php(56): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), true) #5 /srv/Maphper/Maphper.php(97): Maphper\DataSource\Database->save(Object(stdClass)) #6 /srv/index.php(29): Maphper\Maphper->offsetSet(NULL, Object(stdClass)) #7 {main} thrown in /srv/Maphper/DataSource/SqliteAdapter.php on line 27
```
2. I created the table with `sqlite3 sqlite.db "create table blog(id int, name char, age int);"` and now get another error during insert.
```
Fatal error: Uncaught InvalidArgumentException: Record inserted into table blog fails table constraints in /srv/Maphper/DataSource/DatabaseCrud.php:78 Stack trace: #0 /srv/Maphper/DataSource/DatabaseCrud.php(99): Maphper\DataSource\DatabaseCrud->checkIfUpdateWorked(Object(stdClass)) #1 /srv/Maphper/DataSource/DatabaseCrud.php(91): Maphper\DataSource\DatabaseCrud->tryUpdate('blog', Array, Object(stdClass)) #2 /srv/Maphper/DataSource/DatabaseCrud.php(53): Maphper\DataSource\DatabaseCrud->insert('blog', Array, Object(stdClass)) #3 /srv/Maphper/DataSource/DatabaseCrud.php(62): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), false) #4 /srv/Maphper/DataSource/Database.php(56): Maphper\DataSource\DatabaseCrud->save(Object(stdClass), true) #5 /srv/Maphper/Maphper.php(97): Maphper\DataSource\Database->save(Object(stdClass)) #6 /srv/index.php(29): Maphper\Maphper->offsetSet(NULL, Object(stdClass)) #7 {main} thrown in /srv/Maphper/DataSource/DatabaseCrud.php on line 78
```

I don't understand why your test code works fine?
Here is my complete code, which works fine with PDO mysql and fails with PDO sqlite.
```
<?php
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);

// to autoload the class files.
spl_autoload_register(function ($class_name) {
    include_once (__dir__ . '/' . str_replace('\\', '/', $class_name) . '.php');
});

//$pdo = new PDO('mysql:dbname=maphper;host=mysql', 'maphper', 'maphper');
$pdo = new PDO('sqlite:sqlite.db');
//$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_SILENT);

$blogSource = new \Maphper\DataSource\Database($pdo, 'blog', 'id', array('editmode' => true));
$blogs = new \Maphper\Maphper($blogSource);

$blogs[] = (object)$data[0];
```

**Comment by TRPB** [comment]
This works fine as a test:

```php
		unlink('sqlite.db');
		$pdo = new PDO('sqlite:sqlite.db');

		$this->dropTable('blog');
		$data = [
			'name' => 'test'
		];
		$blogSource = new \Maphper\DataSource\Database($pdo, 'blog', 'id', array('editmode' => true));
		$blogs = new \Maphper\Maphper($blogSource);

		$blogs[] = (object)$data;

		$this->assertEquals(count($blogs),  1);
```

**Comment by TRPB** [comment]
Run `composer require --dev level-2/maphper` then write this to a PHP file:

```
 <?php
 require 'vendor/autoload.php';


$pdo = new PDO('sqlite:sqlite.db');


$data = [
	'name' => 'test'
];
$blogSource = new \Maphper\DataSource\Database($pdo, 'blog', 'id', array('editmode' => true));
$blogs = new \Maphper\Maphper($blogSource);

$blogs[] = (object)$data;

var_dump(count($blogs));
```

works as intended. There must be some kind of environment difference.

**Comment by TRPB** [comment]
tested on:

Arch Linux with PHP 7.4.4
A CentOS machine with PHP 7.2.29

**Comment by pwFoo** [comment]
Hi,
after testing with pure PDO sqlite / mysql I found the problem... sqlite.db works fine from console and has correct file permissions, BUT parent directory blocked writes to the file!
PDO doesn't show it as an error, so I found it during testing around with PDO until I enabled warnings / error messages within the PDO object... sorry!!!

Works fine now! :(
